name: Build and Release VibeSenseWidget

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Go to App Folder 🔥
        run: cd app/

      - name: Install Dependencies
        run: npm install
        working-directory: app

      - name: Build App
        run: npm run build
        working-directory: app

      - name: Publish to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run release
        working-directory: app
